version: '3.9'

services:
  movies_admin:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static:/opt/movies_admin/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      custom_network:

  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      custom_network:

  nginx:
    image: nginx:1.23.3
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static:/opt/movies_admin/static
    depends_on:
      - movies_admin
    networks:
      custom_network:
    ports:
      - '80:80'

volumes:
  static:
  postgres:

networks:
  custom_network:
    external: true
