version: "3"

services:
  web:
    build: ./movies_db
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movies_db/:/movies_db/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

volumes:
  postgres_data: