version: "3"

services:
  web:
    build:
      context: ./movies_db
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - static_volume:/home/movies_db/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/movies_db/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: